// ============================================================
// PAWEN — Meta Ads Feedback Loop Types
// Attribution (Pawen output → Meta ad_id)
// Performance (Meta insights per ad)
// Capture (performance-derived gold/rejection signals)
// ============================================================

import type { FunnelType } from '../types';

/**
 * AdAttribution — maps a Pawen creative output to a live Meta ad.
 *
 * Created when a user exports Pawen creatives to Meta Ads Manager.
 * The `meta_ad_id` is filled in later (manually or via the tag-back
 * flow) once the campaign is live in Meta. Before that, the row exists
 * with meta_ad_id = null.
 *
 * This is the join table that connects Pawen output → real performance.
 */
export interface AdAttribution {
  id: string;                          // Pawen-side id (uuid)
  projectId: string;
  projectName: string;
  niche: string;
  language: string;
  targetMarket: string;

  // Which Pawen assets produced this ad
  funnel: FunnelType | null;
  subAvatarId: string | null;
  subAvatarName: string | null;
  subAvatarCategory: string | null;    // experience / emotion / behavior / demographic

  hookId: string | null;               // from gate4 top_hooks
  hookText: string | null;
  hookType: string | null;             // question / number / testimonial / fear / etc.

  headlineId: string | null;           // from gate5/gate7 headline_options
  headlineText: string | null;

  presetId: string | null;             // from gate7 static presets
  presetType: string | null;           // before_after / feature_highlight / etc.

  variantId: string | null;            // which variant of the gate output
  sourceGateIds: string[];             // which gates contributed (e.g. ['gate4', 'gate5', 'gate7'])

  // Link to Meta
  metaAdId: string | null;             // Meta's numeric ad id once live
  metaAdAccountId: string | null;
  metaCampaignId: string | null;
  metaAdsetId: string | null;

  createdAt: string;
  linkedAt: string | null;             // when metaAdId was filled in
}

/**
 * AdPerformance — raw insights pulled from Meta Graph API.
 *
 * One row per ad_id per day. Aggregated over time by the pattern extractor.
 * We keep daily granularity so we can detect creative fatigue (ROAS decay).
 */
export interface AdPerformance {
  id: string;                          // `${meta_ad_id}:${date}`
  metaAdId: string;
  metaAdAccountId: string;
  metaCampaignId: string | null;
  metaAdsetId: string | null;

  date: string;                        // YYYY-MM-DD (UTC)

  // Core metrics from Meta insights
  spend: number;                       // USD
  impressions: number;
  clicks: number;
  ctr: number;                         // clicks / impressions (0-1)
  cpc: number;                         // USD
  cpm: number;                         // USD
  frequency: number;

  // Conversion metrics (require pixel / CAPI setup)
  conversions: number;                 // purchases
  conversionValue: number;             // revenue USD
  cpa: number;                         // spend / conversions
  roas: number;                        // conversionValue / spend
  // Engagement
  videoP50Watched: number | null;      // % that watched 50%
  videoP75Watched: number | null;      // % that watched 75%

  syncedAt: string;                    // when we pulled this from Meta
}

/**
 * PerformanceCapture — the signal we extract from AdPerformance and
 * feed into the Adaptive Learning Engine.
 *
 * Generated by `captureFromPerformance()` after enough spend has accumulated
 * on an ad (threshold: $100 minimum for statistical relevance).
 *
 * Weight is 40 (higher than pick=25, auto_score=15, approval=10) because
 * this signal comes from real market behavior, not internal opinion.
 */
export interface PerformanceCapture {
  id: string;
  attributionId: string;               // → AdAttribution
  metaAdId: string;

  outcome: 'gold' | 'rejection';
  reason: string;                      // e.g. "roas_1.9_over_180_threshold" or "roas_0.3_under_0.5"

  // Aggregated performance at capture time (can update if more data comes in)
  totalSpend: number;
  totalRoas: number;
  totalCtr: number;
  totalConversions: number;
  daysLive: number;

  // Confidence — based on spend volume (more spend = more trust in signal)
  // $100 = 0.3, $500 = 0.6, $2000+ = 1.0
  confidence: number;

  capturedAt: string;
  updatedAt: string;
}

/**
 * PerformancePattern — deterministic statistical insights extracted from
 * the full body of PerformanceCaptures + AdAttributions.
 *
 * Example entries:
 *   { dimension: 'hookType', value: 'question', avgRoas: 2.1, n: 12, winRate: 0.83 }
 *   { dimension: 'funnel', value: 'problem_aware', avgRoas: 1.9, n: 14, winRate: 0.71 }
 *   { dimension: 'subAvatarCategory', value: 'experience', avgRoas: 1.8, n: 8, winRate: 0.75 }
 *
 * Rebuilt periodically by the pattern extractor. Stored as a single
 * document for fast prompt injection (no per-agent DB queries).
 */
export interface PerformancePattern {
  dimension: 'hookType' | 'funnel' | 'subAvatarCategory' | 'presetType' | 'headlineStart' | 'language' | 'niche';
  value: string;                       // e.g. "question", "problem_aware", "experience"
  avgRoas: number;
  medianRoas: number;
  avgCtr: number;
  totalSpend: number;
  winRate: number;                     // % of ads in this bucket with ROAS >= 1.5
  n: number;                           // sample size
  confidence: number;                  // 0-1 based on n and totalSpend
}

export interface PerformancePatternSummary {
  id: string;                          // always 'default'
  version: number;
  patterns: PerformancePattern[];
  // Global stats for calibration
  totalCampaigns: number;
  totalSpend: number;
  avgAccountRoas: number;
  updatedAt: string;
}

// --- Helpers ---

/**
 * Compute confidence score from spend volume.
 * Logarithmic curve: $100 → 0.3, $500 → 0.6, $2000+ → 1.0
 */
export function computeConfidence(spend: number): number {
  if (spend <= 0) return 0;
  if (spend >= 2000) return 1;
  return Math.min(1, Math.log10(spend / 10) / Math.log10(200));
}

/**
 * Gold threshold: ROAS >= 1.8 AND spend >= $100.
 * Rejection threshold: ROAS <= 0.5 AND spend >= $100.
 * Between the two: no signal, wait for more data.
 */
export const GOLD_ROAS_THRESHOLD = 1.8;
export const REJECTION_ROAS_THRESHOLD = 0.5;
export const MIN_SPEND_FOR_SIGNAL = 100;
export const WIN_ROAS_THRESHOLD = 1.5;
